### ISSUE TITLE
Tooling Gorup member update

### ISSUE THREAD

**Issue by haksungjang** [OpenChain-Project/OpenChain-KWG#99]
https://openchain-project.github.io/OpenChain-KWG/subgroup/tooling/

**Comment by haksungjang** [comment]
@JustinWonjaePark 
tooling group 소개 페이지 내 멤버 현황 업데이트가 필요해 보입니다. 처리 가능한지 검토 부탁 드려요. 
곤란할 경우 Assignees를 저로 변경해 주세요. 감사합니다. :)

**Comment by JustinWonjaePark** [comment]
@haksungjang 확인이 늦었습니다!
#104

**Comment by haksungjang** [comment]
감사합니다!
